// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPTbrS_oeQwIeb4Q0_hDvVdAgWVBlX50',
    appId: '1:754276546994:web:9cb825fde62c521f280cab',
    messagingSenderId: '754276546994',
    projectId: 'onesignal-fe135',
    authDomain: 'onesignal-fe135.firebaseapp.com',
    storageBucket: 'onesignal-fe135.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE5fDojIKeM6CFigUXFm8mlfFXN2DQQfk',
    appId: '1:754276546994:android:03095edcea83590e280cab',
    messagingSenderId: '754276546994',
    projectId: 'onesignal-fe135',
    storageBucket: 'onesignal-fe135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCyGl26mFgnN-a-qstXmgjRCbnBlFoGcg',
    appId: '1:754276546994:ios:ea18e9149d5ca120280cab',
    messagingSenderId: '754276546994',
    projectId: 'onesignal-fe135',
    storageBucket: 'onesignal-fe135.firebasestorage.app',
    iosBundleId: 'com.ayomide.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCyGl26mFgnN-a-qstXmgjRCbnBlFoGcg',
    appId: '1:754276546994:ios:ea18e9149d5ca120280cab',
    messagingSenderId: '754276546994',
    projectId: 'onesignal-fe135',
    storageBucket: 'onesignal-fe135.firebasestorage.app',
    iosBundleId: 'com.ayomide.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwPTbrS_oeQwIeb4Q0_hDvVdAgWVBlX50',
    appId: '1:754276546994:web:ed6e0d1cebd2da55280cab',
    messagingSenderId: '754276546994',
    projectId: 'onesignal-fe135',
    authDomain: 'onesignal-fe135.firebaseapp.com',
    storageBucket: 'onesignal-fe135.firebasestorage.app',
  );

}